### PR TITLE
Fix style and optimise

### PR DESCRIPTION
**Pull request by Etua**
This set of commits unifies the style to LLVM's clang-format. It also introduces a variety of optimisations and should make the codebase easier to read. Most of the optimisations (by number) concern getting a value once, instead of in each loop of a function, if the said value doesn't change.

### CODE REVIEW

**Comment by Etua** [comment]
I can fix the conflict tommorow myself. Otherwise you can see how I handled it in the dev branch in my fork.

**Comment by obolo** [comment]
Oh, if you give few days I can fix it too. Regarding the formatting, I was following the GCC guidelines in, e.g., the brackets on newline, but for me it's the same. GCC or LLVM is fine either.  Did you use clang-format?

**Comment by obolo** [comment]
Yes, sorry, you even wrote you used clang-format. Given that you're merging from your fork, I'll wait for your fix, then. Thanks a lot, again

**Comment by Etua** [comment]
Honestly, I just prefer spaces in the value assignments and this brace layout. The rest is not that important. Of course, if you'd prefer something other than LLVM style, please inform me: you are the maintainer after all.

I've merged the changes.

**Comment by obolo** [comment]
Nah. LLVM is fine. Thank you for the fixes.

**Pull request merged**
